### ISSUE TITLE
Fallo de inicio de sesión (user login)

### ISSUE THREAD

**Issue by Ascript89** [aosucas499/guadalinex#1]
Cuando selección la primera opción en el menú de arranque, e intento iniciar sesión con las credenciales dadas, las cuales son correctas (admin - root), se queda la pantalla en negro con el cursor movible por la pantalla, y vuelve al inicio de sesión. Por ende, no pudiendo iniciar sesión.

He cambiado la contraseña del usuario 'admin', y entonces fue cuando ya no admitia ni la nueva contraseña ni la antigua (root).
Intentaré hacer un video de ello pronto y subir el enlace aquí.

**Comment by Ascript89** [comment]
VMware Workstation 16, no he llegado a hacerlo en una maquina de verdad. Antes de iniciar sesion para abrir el instalador. No oficial + plus

**Comment by aosucas499** [comment]
Yo lo he generado e instalo a diario en virtualbox. También lo tengo instalado en varias máquinas reales. Prueba una máquina real y me cuentas porque ni idea de vmware o si me mandas el vídeo y lo vemos. Gracias.
