### ISSUE TITLE
SmartBoard NoteBook

### ISSUE THREAD

**Issue by TheRealDarbyPC** [aosucas499/guadalinex#11]
Seria Factible instalar Smartboard Notebook en EducandOS + ??

Yo lo estoy intentando; pero de momento sin éxito.

**Comment by aosucas499** [comment]
EOS oficial ha puesto la instalación de smartboard con smartnotebook, puedes encontrarla en el centro de software. Con respecto a EOS plus, he añadido una instalación de smartboard, que comprueba que has instalado la oficial y añade los drivers táctil para el modelo 480, pues la instalación oficial me da que no vale para este modelo, ya que no traen los drivers nwfermi.
