### ISSUE TITLE
Drivers iq board 

### ISSUE THREAD

**Issue by jmillup683** [aosucas499/guadalinex#12]
Buenas tardes. Mi pizarra es la versión 7.0. de iq board 
S082LSXNXM7016429A045 ES EL número de serie.
Sería posible tener los comandos para instalación? Muchas gracias

**Comment by aosucas499** [comment]
Te ayudo y vamos viendo por aquí. Espero que te manejes un poco con la terminal, igualmente puedes copiar y pegar los comandos desde aquí. Tenemos que probar, reiniciar y probar si funciona. Te pongo instrucciones:

1. Abrimos terminal e introducimos los siguiente comandos, uno por línea, pulsando la tecla enter al final de cada uno:

```
wget https://github.com/aosucas499/guadalinex/raw/main/src/64%20BITS%20IQBoard%20ET%20%26%20PS%20Drivers%20V7.0.deb

sudo dpkg -i *IQ*.deb
```

2. Reiniciamos y probamos si funciona la pizarra.

Sino funciona, cuéntame aquí si te ha salido algún fallo o lo que hayas observado.

Un saludo.



Como observarás tienes un menú para probar aplicaciones de la pizarra en cada driver que instales.
![IQboard](https://user-images.githubusercontent.com/72696244/135333569-2d26b463-6017-4b80-b62f-155cc20bf7e6.png)

**Comment by jmillup683** [comment]
buenas tardes. Copio el comando y lo pego... se pone a cargar.... cuando termina el proceso me dice contraseña pero no puedo escribir. Creo que lo que no he hecho bien es lo del comando y darle enter a cada uno porque cuando lo pego comienza directamente el proceso. Perdona mi ignorancia con aspectos básicos de linux. gracias

**Comment by aosucas499** [comment]
Te los pongo separados para que los pegues separados.


`wget https://github.com/aosucas499/guadalinex/raw/main/src/64%20BITS%20IQBoard%20ET%20%26%20PS%20Drivers%20V7.0.deb`

`
sudo dpkg -i *IQ*.deb`

Copia desde wget hasta deb y pega en el terminal. Cuando descargue, copia el segundo y pega en el terminal.

La contraseña es la contraseña de tu usuario.

**Comment by jmillup683** [comment]
Buenas no me deja poner la contraseña ciando termina. Algo hago mal. Mañana
le comento. Mil gracias.

**Comment by aosucas499** [comment]
Esta versión no es la oficial. Esto es un proyecto que modifica el sistema original para poder instalar cosas.

Echa un vistazo a este proyecto, la página principal y la wiki. Tienes que instalarlo en tu pc. Y cualquier duda pregunta en los grupos de telegram.


Un saludo.
