### ISSUE TITLE
Intentando crear mi propia version de educaAndos pero tengo problemas.

### ISSUE THREAD

**Issue by Crisespecial** [aosucas499/guadalinex#14]
Estoy intentando crear mi propia versión, hago un truco para que educaAndos me ponga como root pero solo funciona en PCS lentos y además cuando intento usar eggs para crear el ISO se para sin darme ningún error asique como lo has hecho?!

**Comment by aosucas499** [comment]
Primero debes conseguir que tu usuario esté en un grupo con derechos root. Para ello utiliza una live Linux para modificar tu educaandos original. Después mira mucho la documentación de penguin eggs y podrás ir avanzando. Qué modificaciones quieres hacer en la versión?

**Comment by Crisespecial** [comment]
Encontre una ISO en los servidores de educaAndos antes ya no existe asique para que no desaparezca la archive, puedes descargar guadalinex 20.04 aqui:
https://sourceforge.net/projects/guadalinex/files/Guadalinex%2020.04/guadalinexedu-20.04-alpha01.iso/download
La contraseña de esta version de su usuario es usuarioo lee el manual para mas info

**Comment by aosucas499** [comment]
Sí compañero, con esa versión cree mi primera versión de educaandos plus.

**Comment by Crisespecial** [comment]
> Sí compañero, con esa versión cree mi primera versión de educaandos plus.

Supongo que descargaste tu version de guadalinex en la web archive.
Si miras quien lo ha subido a la web archive y al sourceforge vera que soy yo. Solo que ese nombre ya estaba en uso en github.

**Comment by aosucas499** [comment]
No, la descargué de donde se liberó la versión alpha y fue aquí [https://muyguadablog.com/]().

**Comment by aosucas499** [comment]
Este era el enlace original pero el autor borró el post tiempo después. [https://muyguadablog.com/2020/10/12/actualizados-enlaces-disponible-la-version-alpha-de-guadalinex-edu-20-04-heroes/]()

En mis scripts verás que eso fue un proyecto que empezó hace un año, hoy día no lo construyo con la versión alpha sino con la oficial.
