### ISSUE TITLE
Ayuda para crear otros usuarios.

### ISSUE THREAD

**Issue by dcammar111** [aosucas499/guadalinex#2]
Tengo el ordenador de la hp de la junta, e instale la versión plus que pusiste en github, sobre todo por la oportunidad de usar chrome en vez de chromium. Lo cual te agradezco. Me gustaría cambiar los usuarios, pero me sale un mensaje de desbloqueo con el que necesito una clave de administrador, sabrías decirme cual es?, si la sabes. Muchas gracias por tu aportación.

**Comment by aosucas499** [comment]
Buenas noches compañero. Tu usuario creado con esta versión plus lleva la contraseña que tú le hayas puesto y que te da acceso a cualquier tarea administrativa. Pero si te refieres a algunas tareas en las que te pide la contraseña del usuario root, la tienes que crear en la consola de comandos en cada inicio. 

En casa inicio, el sistema oficial y por lo tanto este plus ya que hay cosas que aún no quiero modificar, borra el usuario root si existiese y por lo tanto hay que hacerlo en cada reinicio, restableciendo la contraseña que en verdad no existe.

El procedimiento te lo digo de memoria y sino te va te lo confirmo cuando me contestes:

1. Abre terminal y escribe:
2. `sudo passwd root`
3. Introduce la contraseña de tu usuario
4. Introduce dos veces una contraseña para el usuario root y que luego podrás usar en el procedimiento que me cuentas.
5.  Este proceso se pierde en cada inicio, por lo que tendrás que volver a realizarlo si en alguna tarea se te requiere, que son pocas, ya que tu usuario tiene permisos de administrador.

**Comment by dcammar111** [comment]
Ok, funcionó, muchas gracias

**Comment by aosucas499** [comment]
De nada.
