### ISSUE TITLE
Necesito ayuda tengo que dumpear una version especial sin hacer cambios solo acceso root como usuario que ya he logrado.

### ISSUE THREAD

**Issue by Crisespecial** [aosucas499/guadalinex#22]
Los PC dado a los estudiantes que no tienen un dispositivo en casa tienen una versión especial.
El nombre se cambia aleatoriamente en ese PC solo cuando le da la gana.
Hay una app exclusiva que incluye el manual de uso.
y otras cosas que tendrá internamente.
He hecho una copia de seguridad y la he cargado en una maquina virtual y me gustaria saber como TU instalaste eggs ya que estoy viendo como de vieja es tu version de eggs comparada a la actual.

**Comment by aosucas499** [comment]
No sé si te ayudará pero si es el mismo modelo te sale mejor hacer una instalación limpia, rootear y clonar con clonezilla.

**Comment by Crisespecial** [comment]
> No sé si te ayudará pero si es el mismo modelo te sale mejor hacer una instalación limpia, rootear y clonar con clonezilla.

No voy a hacer eso ya que tu ya has hecho eso. Haber otra cosa que me ha llamado la atencion es que en el fondo verde que trae el sistema dice Slim eso es un bug del sistema porque no hay Slim todavia ademas la version de estos PCS son totalmente diferente y una instalacion limpia se lo cargaria.

**Comment by Crisespecial** [comment]
Oh yeah tengo una pregunta, si ejecuto instalar SmartBoard driver el script que tu hiciste en educandos root. Funcionaria en teoria?

**Comment by aosucas499** [comment]
> > No sé si te ayudará pero si es el mismo modelo te sale mejor hacer una instalación limpia, rootear y clonar con clonezilla.
> 
> No voy a hacer eso ya que tu ya has hecho eso. Haber otra cosa que me ha llamado la atencion es que en el fondo verde que trae el sistema dice Slim eso es un bug del sistema porque no hay Slim todavia ademas la version de estos PCS son totalmente diferente y una instalacion limpia se lo cargaria.

Yo no hice eso. Yo utilicé penguin eggs y herramientas varias. Es una recomendación que te doy para equipos idénticos. No sé que me quieres decir con bugs, eso es tema de educandos oficial, no mía. Ese fondo de escritorio lo pusieron porque tendrán planeado en el futuro incluir versión slim y ese fondo no es el predeterminado.

**Comment by Crisespecial** [comment]
Pero sin instalo tu `SmartBoard Docker` funcionaria en teoria
Y si instalo `HGR Docker` en ubuntu tambien funciona?

**Comment by Crisespecial** [comment]
Bueno un dia subire la copia de seguridad y me pondre en contacto contigo para crear un ISO de esta version.
Solo quiero la ISO sin modificaciones no quiero apps-guadalinex20 ni modificaciones del PLUS.
Yo me ocupare de archivarlo en una carpeta publica en un siteo seguro al lado habra un README que contendra mas detalles sobre esto y por supuesto.

`Gracias a la ayuda del creador de EducaAndos PLUS unofficial aosucas499 se ha podido crear una version instalable de este sistema`

**Comment by aosucas499** [comment]
Te recomiendo que eches un vistazo a la documentación de linux sobre usuarios y grupos. Mi versión, en la instalación cualquier nombre de usuario será admin, no necesitas que sea de nombre admin.
