### ISSUE TITLE
Crear iso educaandos slim plus

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/guadalinex#26]
Al haberse creado una versión de eos slim para dispositivos con menos recursos, sería interesante crear una versión plus, con las mismas características, root y app-guadalinex-20 para instalar dependencias y programas necesarios en los centros.

**Comment by xwa23rihoh** [comment]
Hola soy yo desde el un PC del instituto, antes de que educaAndos slim se creara yo entre en los repos y habia fallos en su firewall y por tiempo limitado se podia entrar a una carpeta de pruebas. Nunca la probe pero las ISO testing como la que alguien puso publica de guadalinex alpha y tenia root es posible que lo que descarge sea la slim si quieres usar PURO slim modifica el archivo etc/sudoers y pon usuario (parametros) abajo del nombre del root.

**Comment by aosucas499** [comment]
Completado

https://github.com/aosucas499/guadalinex/tree/slim
