### ISSUE TITLE
WINE

### ISSUE THREAD

**Issue by Enoth** [aosucas499/guadalinex#30]
Sería interesante que se pudiera instalar WINE, para ejecutar aplicaciones de Windows, aunque no se si será posible.

**Comment by aosucas499** [comment]
Es posible compañero. Pero prefiero que lo añadan desde la versión oficial. Si lo añado, wine tiene varias dependencias y puede provocar conflictos con la versión que añadan posteriormente desde el centro de software oficial. Seguramente lo añadirán pronto, pues siempre lo han añadido en guadalinex. Gracias por la propuesta, si tardan mucho en añadirlo retomo tu propuesta.
