### ISSUE TITLE
cuckoo a PXE server on a live image

### ISSUE THREAD

**Issue by pieroproietti** [aosucas499/guadalinex#34]
¿Cómo son las cosas en España profesor? 

Hace poco añadí una novedad interesante ad eggs para su proyecto y más generalmente para cualquiera que tenga que hacer muchas instalaciones en una red.

La novedad es el comando sudo eggs cuckoo que -introducido directamente desde el terminal- una vez iniciado el live proporciona un servidor PXE autoconfigurado para distribuirlo en la red.

En pocas palabras, es posible arrancar otro u otros ordenadores de la red desde el directo en el que se inició cuckoo.

La magia viene en varias piezas, instalas dnsmasq y el paquete pxelinux y los configuras.

Puede operar en modo proxy-dhcp, sin interferir con el servicio dhcp en la red - y este es el modo por defecto - o iniciando un servicio dhcp real, sólo hay que poner la bandera **--real**. Ejemplo: ```sudo eggs cuchoo --real```,

Esto te permite instalar muchos ordenadores desde uno solo. Todo lo que se necesita para conseguirlo en educandos es remasterizar el proyecto con la nueva versión de huevos.

Os dejo un enlace a una versión de [Ubuntu focal remasterizada](https://sourceforge.net/projects/penguins-eggs/files/ISOS/ubuntu/focal/) con la última versión de eggs.

saludos y espero que le interese

**Comment by aosucas499** [comment]
Hola amigo Piero! Qué bueno tener noticias tuyas.

Pues últimamente muy ocupado por tener la jefatura de estudios de mi centro pero tenía pensado hacer una nueva ISO que traiga todas las actualizaciones del sistema en que se basa el mío para que los profesores no pierdan tiempo en la instalación.

Me viene genial la novedad de eggs, así que generaré la nueva ISO con la nueva versión de eggs y te escribiré para darte feedback.

Muchas gracias por tu trabajo amigo y un fuerte abrazo.

**Comment by aosucas499** [comment]
Hola amigo Piero! Qué bueno tener noticias tuyas.

Pues últimamente muy ocupado por tener la jefatura de estudios de mi centro
pero tenía pensado hacer una nueva ISO que traiga todas las actualizaciones
del sistema en que se basa el mío para que los profesores no pierdan tiempo
en la instalación.

Me viene genial la novedad de eggs, así que generaré la nueva ISO con la
nueva versión de eggs y te escribiré para darte feedback.

Muchas gracias por tu trabajo amigo y un fuerte abrazo.

**Comment by aosucas499** [comment]
Últimas versiones de eos+, eosSlim+ y eos+ con kernel actualizado contienen la versión eggs 9.3.7 con PXE server, queda probarlo.
