### ISSUE TITLE
Perdida de privilegios root

### ISSUE THREAD

**Issue by joseht1988** [aosucas499/guadalinex#35]
Hola, 
Estoy probando la distribución y funciona realmente bien, es una maravilla.
El problema está en que cuando instalas y reinicias, automáticamente se actualiza el SO y tras reiniciar se pierden los privilegios de root así como el + del fondo de escritorio.
¿Tienes previsto solucionarlo?
Gracias

**Comment by aosucas499** [comment]
Así, es, una actualización hace eso.
La solución temporal hasta que produzca una nueva ISO, la tienes en el grupo de Telegram:
[https://t.me/coordinacionTicAndalucia](https://t.me/coordinacionTicAndalucia)
