### ISSUE TITLE
Versión ligera

### ISSUE THREAD

**Issue by Yisus2312** [aosucas499/guadalinex#4]
Buenas!

Es la primera vez que interactúo en Github, no sé si es este el apartado indicado, pero quería preguntarte: hay posibilidad de poder tener la versión 'Slim' de 'EducaAndOS' al igual que la había en Guadalinex? Se podría tener alguna versión optimizada con escritorio LXDE y demás? Gracias de antemano y saludos

**Comment by aosucas499** [comment]
Hola Yisus. 
Este proyecto está basado en añadir mejoras al sistema educaandos sin modificar el sistema original, depende de ellos sacar una versión slim. 

Alguna vez he probado a añadir un escritorio ligero e intentar tener una versión slim pero eso traería problemas de dependencias en paqueres y originaría romper el sistema original, aún así, lo que se conseguiría es tener un lubuntu o xubuntu, por lo que no tiene sentido hacerlo. 

Mi experiencia en el centro por si te vale: en equipos que corren educandos un poco lento, yo les pongo linux mint mate, en verdad educandos es un ubuntu o Linux mint con el fondo de escritorio cambiado, así que te recomiendo lo pruebes, no te va a traer ningún cambio tener un ubuntu mate, xfce, lxde o tener un educandos slim si algún día lo hacen. Como te explico antes hacer una versión slim rompe educaandos por las dependencias que le ponen a los paquetes originales.

Espero haberme explicado bien, cualquier duda escríbeme aquí y lo vemos. Un saludo y gracias por escribir.

**Comment by Yisus2312** [comment]
Gracias por tu respuesta. Soy seguidor del software libre desde hace algunos años y todo lo relacionado con proyectos que impulsa la administración me parecen interesantes y de gran utilidad, igualmente como bien dices, no hay versión ligera y Educaandos se hace pesado en ciertos sistemas imagino que por usar un entorno de escritorio pesado y una estética que consume muchos recursos. Como bien dices, conviene más utilizar Ubuntu, Mint o alguno de los típicos. 
Gracias por tu dedicación con este mini proyecto, estaré atento a cualquier novedad.
Saludos.
