### ISSUE TITLE
Apps-guadalinex-20

### ISSUE THREAD

**Issue by jlmollinedo** [aosucas499/guadalinex#40]
Buenos días, me pongo en contacto porque al instalar educaandos, me sale el siguiente error y tengo conexión a Internet, lo he probado en otros equipos y pasa lo mismo, incluso en otro equipo donde tenía instalada esta versión (la última) y al volver a intentar acceder, no me deja sale ese mensaje. Sin embargo si que sigue estando el usuario con permisos de root. 

![IMG_20221122_105954](https://user-images.githubusercontent.com/118819197/203311974-2349bd15-f898-4ed1-85d1-202ae7433429.jpg)

**Comment by aosucas499** [comment]
1. No puedes instalar con usuarios llamadas admin o usuario.
2. Instala la última ISO subida hace unos días

**Comment by jlmollinedo** [comment]
Hola Andrés, lo que me indicas es como lo he realizado, he vuelto a
descargar la imagen, por si mi pendrive hubiese tenido algún error o
problema, pero tras descargar de nuevo la última imagen y volverla a
instalar el mensaje cuando accedo a Apps-guadalinex-20 es el mismo que te
he expuesto anteriormente "Es necesaria conexión a Internet para poder
utilizar esta app", (y tengo conexión a Internet), por tanto no puedo
instalar nada desde allí. He preguntado en el foro de telegram, para ver si
le está pasando a otros compañeros-as.
Un saludo.

**Comment by aosucas499** [comment]
Contestado en Telegram
