### ISSUE TITLE
GRUB

### ISSUE THREAD

**Issue by IsCa3215** [aosucas499/guadalinex#41]
Hola, cuando instalo la ISO oficial de HP probook 455 g7 me manda al grub y no hay manera de hacerlo arrancar. Gracias.

**Comment by aosucas499** [comment]
Este proyecto es sobre educandos plus no oficial, la oficial no tiene soporte aquí.
Recuerda que la oficial solo se puede grabar con las aplicaciones de Educaandos de grabador de USB, nunca con etcher.
