### ISSUE TITLE
escritorio lxde en ciertos equipos.

### ISSUE THREAD

**Issue by chipygr** [aosucas499/guadalinex#42]
Buenas tardes.
Te comenté por telegram el problema de que se me iniciaba con escritorio lxde 20.04, y que en una serie de portatiles que tenia mi centro, me dañaba el teclado haciendolo inservible por lo que instalé lubuntu.

Con la salida de la nueva versión, he detectado dos cosas:
1- Los portatiles funcionan con la nueva versión....
2- He probado otra vez en los pc que iniciaban escritorio lxde y sigue haciéndolo pero..... si le pongo un usuario sin root.... TACHAN!! aparace educandoos Slim...
No es un problema en si, pero si creo que hay cierta información que puede serte util. Yo lo sigo flipando.

En telegram soy loroexp por si quieres recordar de lo que hablamos.

**Comment by aosucas499** [comment]
Gracias por la info, viene genial, alguna vez investigaré.
Recuerdo la conversación que tuvimos, esos portátiles con la bios en solo uefi. Esas cosas las hacía también las lamentablets con minino, son dispositivos baratos que no siguen normas de arranque etc....
Yo por más que pruebo en máquina virtual o en los pc's del cole todo me va bien...no puedo ayudarte mucho con esos dispositivos

**Comment by aosucas499** [comment]
Lo único que puedes hacer es instalarlo si te gusta para esos portátiles con un usuario administrador para instalar cosas y dejar para los usuarios un usuario sin derechos que funcione bien con Eos Slim plus...de hecho así lo tengo yo en todos los pc's...
