### ISSUE TITLE
Configuración | sonido | salida --> se cambia al reiniciar

### ISSUE THREAD

**Issue by dess013** [aosucas499/guadalinex#43]
Hola, tengo este problema en un PC, conectado a una pizarra Promethean y el sonido en altavoces externos. Lo pongo en configuración | sonido | salida --> audio de salida - audio interno, todo perfecto, sonido por los altavoces... pero al iniciar el sistema de nuevo se ha cambiado por otra opción. no se guarda el cambio, hay que hacerlo cada vez que se inicia el sistema. ¿como guardo los cambios? ¿tiene solución?
Mil gracias de antemano, por tu generoso trabajo.

**Comment by aosucas499** [comment]
Hola compañero, tengo algunos clases así configuradas, y no suelen dar problemas, aunque alguna vez sí que cambian el sonido.
La solución para por saber utilizar la terminal, si tienes algunos conocimientos puedes establecer la salida de audio predeterminada. Te mando algunos tutoriales de la web. Haz alguna búsqueda que te interese teniendo en cuenta que el sistema está basado en Ubuntu 20.04 y el gestor de ventanas es gnome.

[https://www.google.com/search?q=ubuntu+20.04+sound+out+change+every+boot&oq=ubuntu+20.04+sound+out+change+every+boot](búsqueda )
