### ISSUE TITLE
¿Es posible crear un USB Live de esta versión?

### ISSUE THREAD

**Issue by JuaneteMii** [aosucas499/guadalinex#44]
Hola, estoy instalando esta versión de Ubuntu porque tengo un MacBook al cual le falla la SSD y quiero usarlo para la escuela, que no requiere de almacenamiento. Pero, no sé si hay manera de hacer un USB que sí guarde los archivos y configuraciones.

**Comment by aosucas499** [comment]
Hola compañero. La versión de Educaandos original o plus no está diseñado para tal fin, aunque al estar basado en Ubuntu puedes probar algo y me cuentas si te funciona.
En lugar de grabar en el pendrive con etcher, intenta grabarla con Rufus (necesitarás algún tutorial en la red para seleccionar las opciones adecuadas) y en el apartado "pesistent partition size" dale el valor que quieres que guarde el USB para guardas tus datos que no se borren.
Prueba a ver qué tal

**Comment by JuaneteMii** [comment]
¡Gracias! Mañana lo intentaré a ver si lo consigo.
