### ISSUE TITLE
Error al instalar aplicaciones de la tienda

### ISSUE THREAD

**Issue by pcascar3005** [aosucas499/guadalinex#48]
hola, cuando quiero instalar una aplicacion desde la tienda me da este error.
![Captura de pantalla de 2023-04-29 09-18-57](https://user-images.githubusercontent.com/123895754/235289472-ee7c7a7f-c64a-4d7f-a680-24a6e36d8115.png)

**Comment by aosucas499** [comment]
Creo que es un fallo típico de la versión oficial porque no encuentra el usuario= usuario.
Sí esa instalación la has hecho justo después de actualizarse algo, reinicia y prueba otra vez. 
En caso contrario crea un usuario llamado usuario y prueba otra vez.

**Comment by pcascar3005** [comment]
y cuando instalo algo desde la terminal me dan error el cga-grub y el cga-congelador

**Comment by aosucas499** [comment]
Sí, ese es el fallo, corrígelo como te puse en el comentario anterior.

**Comment by pcascar3005** [comment]
los programas los instalo desde la cuenta usuario?

**Comment by aosucas499** [comment]
No, crear el usuario usuario y luego haces los otro desde la cuenta que usas ahora.

**Comment by pcascar3005** [comment]
ok, gracias
