### ISSUE TITLE
ERROR DE INSTALACIÓN EDUCAANDOS + 

### ISSUE THREAD

**Issue by jringal909** [aosucas499/guadalinex#6]
Buenos días.
Queremos instalar esta versión en todos losportátiles windows del centro pero nos ha dado problemas con un lenovo v110. Tras la instalación y el reinicio, aparece una pantalla con el BOOT MENU y de ahí no sale.  No sé si me puedes ayudar.

Gracias y enhorabuena por tu trabajo.

Un saludo.

Juan Carlos.

**Comment by aosucas499** [comment]
Buenas compañero. 
Te puedo echar un cable si me das más información y fotos.

Tenías Windows instalado? Lo has mantenido o borrado todo con educandos? Has arrancado el usb en modo normal bios o modo uefi? Un saludo.

**Comment by jringal909** [comment]
Buenos días. En primer lugar, gracias por tu ayuda. El ordenador es un LENOVO V110 (un poco básico) que tenía instalado W10. En las instrucciones de instalación, he seguido la opción de borrado. Después he arrancado en modo normal, sin el pendrive. Adjunto imagen de la pantalla que me sale al iniciar y que sale en bucle con cualquier opción que elijas.
https://drive.google.com/file/d/1ZwR142SNWEDjxiVSADXpHAhGaWzczyxy/view?usp=sharing
Un saludo.

**Comment by aosucas499** [comment]
Tienes que entrar en la bios y seleccionar la opción para arrancar desde el pendrive. Si sales dos opciones para el pendrive, elije uefi.

**Comment by jringal909** [comment]
> Tienes que entrar en la bios y seleccionar la opción para arrancar desde el pendrive. Si salen dos opciones para el pendrive, elije uefi.

Tras la instalación hay que volver a reiniciar con el pen drive? Porque ya hice la instalación. El problema ha venido tras el reinicio, donde se pone esta pantalla.

**Comment by aosucas499** [comment]
No, cuando acabe quita el pendrive e inicia el pc.

**Comment by jringal909** [comment]
Eso hice. Y no arranca el portátil. Lo intentaré con otro dispositivo.

**Comment by aosucas499** [comment]
Sí, los errores más comunes son algún fallo en la descarga o usar otro pendrive. Algunos pendrives parece que van bien pero fallan al grabar una iso. Prueba otro pendrive si te falla.

**Comment by jringal909** [comment]
Muchas gracias. lo voy a intentar con otro pen drive, a ver qué tal.

**Comment by aosucas499** [comment]
Se solucionó?
