### ISSUE TITLE
Windows 10 + educaandos

### ISSUE THREAD

**Issue by ego-pc** [aosucas499/guadalinex#61]
Hola. Tengo Windows 10 instalado. ¿Es posible instalar educandos sin quitar Windows 10 y elegir con arranque dual? En caso afirmativo, ¿Cómo tendría que configurar las particiones?

**Comment by aosucas499** [comment]
No doy soporte a sistemas privativos como Windows . Busca información sobre cómo hacerlo con instalador calamares o Ubuntu 20, el tema de particiones es igual.
