### ISSUE TITLE
Educandos Plus en pizarras IQBoard

### ISSUE THREAD

**Issue by Gemagamez** [aosucas499/guadalinex#9]
Buenos días, en mi IES tenemos 4 pizarras IQBoard, modelo TN082 y me gustaría instalarles Educandos Plus. ¿Hay drivers específicos para estas pizarras?
Muchísimas gracias por tu gran trabajo.

**Comment by aosucas499** [comment]
Buenas compañero.

No tengo drivers para esa pizarra. Supongo que son compradas por el centro y no me suenan que tuvieran soporte en los antiguos guadalinex.  Si quieres  puedo investigar y si se puede añadirlas. Una pregunta, ¿en qué sistema funcionaban antiguamente?

**Comment by aosucas499** [comment]
He encontrado estos drivers para tu pizarra, podrás ver el enlace buscando por tu modelo TN082. Si quieres te indico cómo instarlos en educandos plus.

[https://iqboard.com.es/soporte-tecnico/]()

[https://mega.nz/folder/fcMHXShD#Q7_aFf24AvVxHjiYyx6BPQ]()

**Comment by Gemagamez** [comment]
Buenas! Estaban en Windows 10. Sí, fueron compradas por el centro. Este es mi segundo año como coordinadora y me propuse que todas las PDI tuvieran Educandos Plus, os leí por el grupo de Telegram y por eso me atreví a escribirte. Sé que estás muy ocupado, si no puedes, no te preocupes. 

💎

**Comment by Gemagamez** [comment]
Te lo agradecería mucho! Esto de la coordinación TDE me viene un poco grande a veces 🥲

💎

**Comment by aosucas499** [comment]
Te ayudo y vamos viendo por aquí. Espero que te manejes un poco con la terminal, igualmente puedes copiar y pegar los comandos desde aquí. El problema es que el fabricante tiene dos drivers para este module. Tenemos que probar uno, reiniciar, probar si funciona y en caso contrario, borrar el primero e instalar el segundo. Te pongo instrucciones:

1. Abrimos terminal e introducimos los siguiente comandos, uno por línea, pulsando la tecla enter al final de cada uno:

```
wget https://github.com/aosucas499/guadalinex/raw/main/src/06%20DVTQ-N%206-10%20TOQUES.zip

unzip *TOQUES.zip

cd x64

sudo dpkg -i *14*.deb
```

2. Reiniciamos y probamos si funciona la pizarra.

3. Sino funciona al igual que antes introducimos los siguiente comandos, uno por línea, pulsando la tecla enter al final de cada uno:

```
cd x64

sudo dpkg -P rsboarddvtq

 sudo dpkg -i *18*.deb
```

4. Reiniciamos y comprobamos que funciona. En caso contrario cuéntame aquí si te ha salido algún fallo o lo que hayas observado.

Un saludo.

**Comment by Gemagamez** [comment]
Buenas tardes, no me he podido poner esta semana. Hemos estado a tope con las evaluaciones iniciales, y averías varias y no he tenido tiempo. La semana que viene lo intentaré y te cuento.
Saludos!

💎

**Comment by aosucas499** [comment]
Cómo va eso? Por cerrar este issue si funcionó.

**Comment by Gemagamez** [comment]
¡Buenas! Perdona, es que tengo sólo los recreos y no había podido hacerlo. Ha ido perfecto de la primera forma. ¡Muchas gracias!👏🏼👏🏼👏🏼

💎

**Comment by aosucas499** [comment]
Genial!!!
